# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "C:\Users\flori\Documents\Nouveau dossier (2)\PROJETINFOS2"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "C:\Users\flori\Documents\Nouveau dossier (2)\PROJETINFOS2"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "C:\Users\flori\Documents\Nouveau dossier (2)\PROJETINFOS2\CMakeFiles" "C:\Users\flori\Documents\Nouveau dossier (2)\PROJETINFOS2\\CMakeFiles\progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "C:\Users\flori\Documents\Nouveau dossier (2)\PROJETINFOS2\CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Projet_INFO_SEM2

# Build rule for target.
Projet_INFO_SEM2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 Projet_INFO_SEM2
.PHONY : Projet_INFO_SEM2

# fast build rule for target.
Projet_INFO_SEM2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Projet_INFO_SEM2.dir\build.make CMakeFiles/Projet_INFO_SEM2.dir/build
.PHONY : Projet_INFO_SEM2/fast

#=============================================================================
# Target rules for targets named doc

# Build rule for target.
doc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 doc
.PHONY : doc

# fast build rule for target.
doc/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\doc.dir\build.make CMakeFiles/doc.dir/build
.PHONY : doc/fast

affichage.obj: affichage.c.obj
.PHONY : affichage.obj

# target to build an object file
affichage.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Projet_INFO_SEM2.dir\build.make CMakeFiles/Projet_INFO_SEM2.dir/affichage.c.obj
.PHONY : affichage.c.obj

affichage.i: affichage.c.i
.PHONY : affichage.i

# target to preprocess a source file
affichage.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Projet_INFO_SEM2.dir\build.make CMakeFiles/Projet_INFO_SEM2.dir/affichage.c.i
.PHONY : affichage.c.i

affichage.s: affichage.c.s
.PHONY : affichage.s

# target to generate assembly for a file
affichage.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Projet_INFO_SEM2.dir\build.make CMakeFiles/Projet_INFO_SEM2.dir/affichage.c.s
.PHONY : affichage.c.s

eclair.obj: eclair.c.obj
.PHONY : eclair.obj

# target to build an object file
eclair.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Projet_INFO_SEM2.dir\build.make CMakeFiles/Projet_INFO_SEM2.dir/eclair.c.obj
.PHONY : eclair.c.obj

eclair.i: eclair.c.i
.PHONY : eclair.i

# target to preprocess a source file
eclair.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Projet_INFO_SEM2.dir\build.make CMakeFiles/Projet_INFO_SEM2.dir/eclair.c.i
.PHONY : eclair.c.i

eclair.s: eclair.c.s
.PHONY : eclair.s

# target to generate assembly for a file
eclair.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Projet_INFO_SEM2.dir\build.make CMakeFiles/Projet_INFO_SEM2.dir/eclair.c.s
.PHONY : eclair.c.s

entrees.obj: entrees.c.obj
.PHONY : entrees.obj

# target to build an object file
entrees.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Projet_INFO_SEM2.dir\build.make CMakeFiles/Projet_INFO_SEM2.dir/entrees.c.obj
.PHONY : entrees.c.obj

entrees.i: entrees.c.i
.PHONY : entrees.i

# target to preprocess a source file
entrees.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Projet_INFO_SEM2.dir\build.make CMakeFiles/Projet_INFO_SEM2.dir/entrees.c.i
.PHONY : entrees.c.i

entrees.s: entrees.c.s
.PHONY : entrees.s

# target to generate assembly for a file
entrees.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Projet_INFO_SEM2.dir\build.make CMakeFiles/Projet_INFO_SEM2.dir/entrees.c.s
.PHONY : entrees.c.s

jeu.obj: jeu.c.obj
.PHONY : jeu.obj

# target to build an object file
jeu.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Projet_INFO_SEM2.dir\build.make CMakeFiles/Projet_INFO_SEM2.dir/jeu.c.obj
.PHONY : jeu.c.obj

jeu.i: jeu.c.i
.PHONY : jeu.i

# target to preprocess a source file
jeu.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Projet_INFO_SEM2.dir\build.make CMakeFiles/Projet_INFO_SEM2.dir/jeu.c.i
.PHONY : jeu.c.i

jeu.s: jeu.c.s
.PHONY : jeu.s

# target to generate assembly for a file
jeu.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Projet_INFO_SEM2.dir\build.make CMakeFiles/Projet_INFO_SEM2.dir/jeu.c.s
.PHONY : jeu.c.s

main.obj: main.c.obj
.PHONY : main.obj

# target to build an object file
main.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Projet_INFO_SEM2.dir\build.make CMakeFiles/Projet_INFO_SEM2.dir/main.c.obj
.PHONY : main.c.obj

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Projet_INFO_SEM2.dir\build.make CMakeFiles/Projet_INFO_SEM2.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Projet_INFO_SEM2.dir\build.make CMakeFiles/Projet_INFO_SEM2.dir/main.c.s
.PHONY : main.c.s

menu.obj: menu.c.obj
.PHONY : menu.obj

# target to build an object file
menu.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Projet_INFO_SEM2.dir\build.make CMakeFiles/Projet_INFO_SEM2.dir/menu.c.obj
.PHONY : menu.c.obj

menu.i: menu.c.i
.PHONY : menu.i

# target to preprocess a source file
menu.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Projet_INFO_SEM2.dir\build.make CMakeFiles/Projet_INFO_SEM2.dir/menu.c.i
.PHONY : menu.c.i

menu.s: menu.c.s
.PHONY : menu.s

# target to generate assembly for a file
menu.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Projet_INFO_SEM2.dir\build.make CMakeFiles/Projet_INFO_SEM2.dir/menu.c.s
.PHONY : menu.c.s

sauvegarde.obj: sauvegarde.c.obj
.PHONY : sauvegarde.obj

# target to build an object file
sauvegarde.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Projet_INFO_SEM2.dir\build.make CMakeFiles/Projet_INFO_SEM2.dir/sauvegarde.c.obj
.PHONY : sauvegarde.c.obj

sauvegarde.i: sauvegarde.c.i
.PHONY : sauvegarde.i

# target to preprocess a source file
sauvegarde.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Projet_INFO_SEM2.dir\build.make CMakeFiles/Projet_INFO_SEM2.dir/sauvegarde.c.i
.PHONY : sauvegarde.c.i

sauvegarde.s: sauvegarde.c.s
.PHONY : sauvegarde.s

# target to generate assembly for a file
sauvegarde.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Projet_INFO_SEM2.dir\build.make CMakeFiles/Projet_INFO_SEM2.dir/sauvegarde.c.s
.PHONY : sauvegarde.c.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... doc
	@echo ... Projet_INFO_SEM2
	@echo ... affichage.obj
	@echo ... affichage.i
	@echo ... affichage.s
	@echo ... eclair.obj
	@echo ... eclair.i
	@echo ... eclair.s
	@echo ... entrees.obj
	@echo ... entrees.i
	@echo ... entrees.s
	@echo ... jeu.obj
	@echo ... jeu.i
	@echo ... jeu.s
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
	@echo ... menu.obj
	@echo ... menu.i
	@echo ... menu.s
	@echo ... sauvegarde.obj
	@echo ... sauvegarde.i
	@echo ... sauvegarde.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

